<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition="$(IsWindows)">$(TargetFrameworks);net472;</TargetFrameworks>
    <DisableFody>true</DisableFody>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
  </ItemGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <!--to fix the error: "Could not load file or assembly System.Reflection.Metadata" when running tests on net472 using GitHub action-->
    <PackageReference Include="System.Reflection.Metadata" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MoreFodyHelpers\MoreFodyHelpers.csproj" />
  </ItemGroup>
</Project>
